#!/bin/bash
cd /var/www # zmiana katalogu na /var/www
for FILE in *.html # dla każdego pliku z rozszerzeniem .html
do # wykonaj
	echo "Copying $FILE" # wyświetl komunikat
	cp $FILE /var/www-just-html # skopiuj plik do katalogu /var/www-just-html
done # koniec pętli
